# Generated by Django 2.2.3 on 2019-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bladechassis',
            fields=[
                ('bladeChassisId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bladeChassisNo', models.IntegerField()),
                ('bladeChassisSerial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='bladeinfo',
            fields=[
                ('bladeId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bladeNo', models.IntegerField()),
                ('bladeSerial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='esxi',
            fields=[
                ('inventoryID', models.CharField(max_length=30)),
                ('esxiid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ipaddress', models.GenericIPAddressField()),
                ('bladechassisNo', models.IntegerField()),
                ('bladeNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='serverinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='servertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverType', models.CharField(max_length=30)),
            ],
        ),
    ]
