# Generated by Django 2.2.3 on 2019-08-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataCenterModel',
            fields=[
                ('datacenterId', models.AutoField(primary_key=True, serialize=False)),
                ('datacenterName', models.CharField(max_length=30)),
                ('datacenterCode', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('creationDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='deviceModel',
            fields=[
                ('deviceId', models.AutoField(primary_key=True, serialize=False)),
                ('deviceSn', models.CharField(max_length=30)),
                ('unitUStart', models.IntegerField()),
                ('unitUEnd', models.IntegerField()),
                ('deviceType', models.CharField(max_length=30)),
                ('modelNumber', models.CharField(max_length=30)),
                ('productId', models.CharField(max_length=30)),
                ('warrentyStatus', models.CharField(max_length=30)),
                ('warrentyExpireyDate', models.DateField(auto_now_add=True)),
                ('note', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='networkModel',
            fields=[
                ('networkId', models.AutoField(primary_key=True, serialize=False)),
                ('ipaddress', models.GenericIPAddressField()),
                ('note', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.deviceModel')),
            ],
        ),
        migrations.CreateModel(
            name='rackModel',
            fields=[
                ('rackId', models.AutoField(primary_key=True, serialize=False)),
                ('rackNo', models.IntegerField()),
                ('rackLocation', models.CharField(max_length=30)),
                ('rackName', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('datacenterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dataCenterModel')),
            ],
        ),
        migrations.CreateModel(
            name='serverModel',
            fields=[
                ('serverId', models.AutoField(primary_key=True, serialize=False)),
                ('ServerIP', models.GenericIPAddressField()),
                ('Servername', models.CharField(max_length=30)),
                ('isPhysical', models.CharField(max_length=30)),
                ('osFamily', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
                ('hostName', models.CharField(max_length=30)),
                ('memory', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
                ('environamnt', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.deviceModel')),
            ],
        ),
        migrations.CreateModel(
            name='serverVirtualModel',
            fields=[
                ('vServerId', models.AutoField(primary_key=True, serialize=False)),
                ('ServerIP', models.GenericIPAddressField()),
                ('serverName', models.CharField(max_length=30)),
                ('osFamily', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=30)),
                ('memory', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('Disk', models.IntegerField()),
                ('datastores', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('environamnt', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.deviceModel')),
            ],
        ),
        migrations.CreateModel(
            name='vendorModel',
            fields=[
                ('vendorID', models.AutoField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=30)),
                ('contactNumber', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bladechassis',
        ),
        migrations.DeleteModel(
            name='bladeinfo',
        ),
        migrations.DeleteModel(
            name='center',
        ),
        migrations.DeleteModel(
            name='esxi',
        ),
        migrations.DeleteModel(
            name='serverinfo',
        ),
        migrations.DeleteModel(
            name='servertype',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='rackId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rackModel'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendorModel'),
        ),
    ]
